//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Projects/Elsa/experimental/src/dsl/Elsa.Dsl/Dsl\ElsaParser.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ElsaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface IElsaParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] ElsaParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrigger([NotNull] ElsaParser.TriggerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] ElsaParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.activity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActivity([NotNull] ElsaParser.ActivityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence([NotNull] ElsaParser.SequenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] ElsaParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.localVarDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVarDecl([NotNull] ElsaParser.LocalVarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ElsaParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] ElsaParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] ElsaParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] ElsaParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] ElsaParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.block_statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statements([NotNull] ElsaParser.Block_statementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.block_pairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_pairs([NotNull] ElsaParser.Block_pairsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.pairList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPairList([NotNull] ElsaParser.PairListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] ElsaParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] ElsaParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] ElsaParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>return</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] ElsaParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockStatements</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStatements([NotNull] ElsaParser.BlockStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableDeclaration</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] ElsaParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>localVariableDeclaration</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] ElsaParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assignment</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] ElsaParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expression</c>
	/// labeled alternative in <see cref="ElsaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] ElsaParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>add</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdd([NotNull] ElsaParser.AddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parentheses</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentheses([NotNull] ElsaParser.ParenthesesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>compare</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompare([NotNull] ElsaParser.CompareContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>methodInvocation</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodInvocation([NotNull] ElsaParser.MethodInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>subtract</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtract([NotNull] ElsaParser.SubtractContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableReference</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableReference([NotNull] ElsaParser.VariableReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>increment</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncrement([NotNull] ElsaParser.IncrementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>brackets</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBrackets([NotNull] ElsaParser.BracketsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>not</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] ElsaParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringValue</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringValue([NotNull] ElsaParser.StringValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>negate</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegate([NotNull] ElsaParser.NegateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decrement</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecrement([NotNull] ElsaParser.DecrementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionCall</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] ElsaParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>integerValue</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerValue([NotNull] ElsaParser.IntegerValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiply</c>
	/// labeled alternative in <see cref="ElsaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiply([NotNull] ElsaParser.MultiplyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElsaParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprList([NotNull] ElsaParser.ExprListContext context);
}
